modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${issue_tracker}"
logoFile="logo.png"

[[mods]]
modId="botania"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://botaniamod.net"
description="${mod_description}"
authors="${authors}"
itemIcon="${item_icon}" 
configBackground="${background}" 

[[mixins]]
config="botania.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="patchouli"
    type="required"
    versionRange="[${patchouli_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    type="optional"
    versionRange="[${curios_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kubejs"
    type="optional"
    versionRange="[${kubejs_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="rhino"
    type="optional"
    versionRange="[${rhino_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="wthit"
    type="optional"
    versionRange="[${wthit_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jade"
    type="optional"
    versionRange="[${jade_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="roughlyenoughitems"
    type="optional"
    versionRange="[${rei_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="[${jei_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="emi"
    type="optional"
    versionRange="[${emi_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="ears"
    type="optional"
    versionRange="[${ears_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="sodium"
    type="optional"
    versionRange="[${sodium_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="botanypots"
    type="optional"
    versionRange="[${botanypots_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ponder"
    type="optional"
    versionRange="[${ponder_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="ars_nouveau"
    type="optional"
    versionRange="${ars_nouveau_version_range}"
    ordering="AFTER"
    side="BOTH"
