package velrondevs.botania.client.patchouli;

import net.minecraft.client.Minecraft;
import net.minecraft.core.HolderLookup;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.item.crafting.Recipe;
import net.minecraft.world.item.crafting.RecipeHolder;
import net.minecraft.world.item.crafting.RecipeInput;
import net.minecraft.world.item.crafting.RecipeType;
import net.minecraft.world.level.Level;

import velrondevs.botania.api.BotaniaAPI;
import velrondevs.botania.registry.BotaniaRecipeTypes;
import velrondevs.botania.xplat.XplatAbstractions;
import vazkii.patchouli.api.IVariable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class PatchouliUtils {
	private static boolean crafttweakerInfoNote = false;
	private static boolean inVisualizer;

	public static <T extends Recipe<I>, I extends RecipeInput> T getRecipe(Level level, RecipeType<T> type, ResourceLocation id) {
		RecipeHolder<T> holder = getRecipeHolder(level, type, id);
		return holder == null ? null : holder.value();
	}

	public static <T extends Recipe<I>, I extends RecipeInput> RecipeHolder<T> getRecipeHolder(Level level, RecipeType<T> type, ResourceLocation id) {
		Map<ResourceLocation, T> map = BotaniaRecipeTypes.getRecipes(level, type);
		for (ResourceLocation candidate : List.of(id,
				ResourceLocation.fromNamespaceAndPath("crafttweaker", id.getPath()),
				ResourceLocation.fromNamespaceAndPath("crafttweaker", "autogenerated/" + id.getNamespace() + "." + id.getPath()))) {
			T r = map.get(candidate);
			if (r != null) {
				return new RecipeHolder<>(candidate, r);
			}
		}

		BotaniaAPI.LOGGER.warn("Template references nonexistent recipe {} of type {}", id, type);
		if (!crafttweakerInfoNote) {
			crafttweakerInfoNote = true;
			if (XplatAbstractions.INSTANCE.isModLoaded("crafttweaker")) {
				BotaniaAPI.LOGGER.info("""
					To add a recipe that replaces a builtin recipe with CT,\s
					add one with the same type, named the same as the path of the missing recipe.
					eg. for recipe {}, add a recipe named "{}".""", id, id.getPath());
			}
		}
		return null;
	}

	public static <T extends Recipe<I>, I extends RecipeInput> List<T> getRecipeGroup(RecipeType<T> type, String group) {
		Map<ResourceLocation, T> map = BotaniaRecipeTypes.getRecipes(Minecraft.getInstance().level, type);
		List<T> list = new ArrayList<>();
		for (T value : map.values()) {
			if (group.equals(value.getGroup())) {
				list.add(value);
			}
		}
		if (list.isEmpty()) {
			BotaniaAPI.LOGGER.warn("Template references empty group {} of recipe type {}", group, type);
		}
		return list;
	}

	public static IVariable interweaveIngredients(List<Ingredient> ingredients, int longestIngredientSize, HolderLookup.Provider registries) {
		if (ingredients.size() == 1) {
			return IVariable.wrapList(Arrays.stream(ingredients.get(0).getItems()).map(v -> IVariable.from(v, registries)).collect(Collectors.toList()), registries);
		}

		ItemStack[] empty = { ItemStack.EMPTY };
		List<ItemStack[]> stacks = new ArrayList<>();
		for (Ingredient ingredient : ingredients) {
			if (ingredient != null && !ingredient.isEmpty()) {
				stacks.add(ingredient.getItems());
			} else {
				stacks.add(empty);
			}
		}
		List<IVariable> list = new ArrayList<>(stacks.size() * longestIngredientSize);
		for (int i = 0; i < longestIngredientSize; i++) {
			for (ItemStack[] stack : stacks) {
				list.add(IVariable.from(stack[i % stack.length], registries));
			}
		}
		return IVariable.wrapList(list, registries);
	}

	public static IVariable interweaveIngredients(List<Ingredient> ingredients, HolderLookup.Provider registries) {
		return interweaveIngredients(ingredients, ingredients.stream().mapToInt(ingr -> ingr.getItems().length).max().orElse(1), registries);
	}

	public static boolean isInVisualizer() {
		return inVisualizer;
	}

	public static void setInVisualizer(boolean inVisualization) {
		PatchouliUtils.inVisualizer = inVisualization;
	}
}
